/**
 * @typedef {string} BaseUnit - The base unit of measurement.
 */

/**
 * Enum for mass-based base units.
 * @readonly
 * @enum {BaseUnit}
 */
export const MassUnit = Object.freeze({
    GRAM: 'gram',
    KILOGRAM: 'kilogram',
});

/**
 * Enum for volume-based base units.
 * @readonly
 * @enum {BaseUnit}
 */
export const VolumeUnit = Object.freeze({
    MILLILITER: 'milliliter',
    DECILITER: 'deciliter',
    LITER: 'liter',
});

/**
 * @typedef {Object} Product
 * @property {number} [id] - Auto incremented primary key.
 * @property {string} [gtin] - Global Trade Item Number (optional).
 * @property {string} name - Name of the product.
 * @property {BaseUnit} baseUnit - The base stock unit.
 * @property {PackagingMap} packaging - Map of packaging types and their quantities.
 */

/**
 * A map of packaging types to their corresponding quantity in base units. E.g. {'box': 100, 'pack': 10}
 * @typedef {{
 * bag?: number;
 * box?: number;
 * carton?: number;
 * pack?: number;
 * }} PackagingMap
 */

/**
 * @typedef {Object} Stock
 * @property {number} [id] - Auto incremented primary key.
 * @property {number} productId - Foreign key referencing the product.
 * @property {number} quantity - Current stock quantity in the checked-in unit.
 * @property {keyof PackagingMap} unit - The checked-in unit code (matches a key in packagings).
 * @property {string} [updatedAt] - ISO 8601 timestamp of the last stock update.
 */

/**
 * @typedef {Object} ProductStock
 * @property {Product} product
 * @property {Stock} stock
 */

/**
 * @typedef {Object} ProductInput
 * @property {number} [id] - Unique identifier for the product (optional, generated by DB if not provided).
 * @property {string} [gtin] - Global Trade Item Number (optional).
 * @property {string} name - Display name of the product.
 * @property {string} unit - The fundamental unit of measurement.
 * @property {PackagingMap} packagings - Map of packaging types and their quantities.
 */

export {};